{% set name = "xeofs" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xeofs-{{ version }}.tar.gz
  sha256: 822c5cbd2f48cdde24155e1e8fc2e4a36923e7819483285abecc59c2aeeee6f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - poetry-core >=1.0.0
    - python >=3.10
  run:
    - numpy >=1.19.2,<2.0.0
    - pandas >=1.4.1,<2.0.0
    - pooch >=1.6.0,<2.0.0
    - python >=3.10
    - scikit-learn >=1.0.2,<2.0.0
    - dask >= 2023.0.1
    - scipy >= 1.7.1
    - statsmodels >= 0.14.0
    - xarray >=0.21.1
    - tqdm >=4.64.0,<5.0.0

test:
  imports:
    - xeofs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nicrie/xeofs
  summary: Collection of EOF analysis and related techniques for climate science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicrie
