{% set name = "xeofs" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xeofs-{{ version }}.tar.gz
  sha256: 407d3ae7edf2721624ec2a1e43442cf4fbd90ec778ee005bf9be50ad22ea57bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - poetry >=1.5
    - poetry-core >=1.5
    - python >=3.10,<3.12
  run:
    - numpy >=1.24,<1.25
    - numba >=0.57,<0.58
    - pandas >=1.4.1,<2.0.0
    - pooch >=1.6.0,<2.0.0
    - python >=3.10,<3.12
    - poetry >=1.5
    - scikit-learn >=1.0.2,<2.0.0
    - dask >=2023.0.1
    - scipy >=1.7.1
    - statsmodels >=0.14.0
    - xarray >=0.21.1
    - netCDF4 >=1.5.7
    - tqdm >=4.64.0,<5.0.0
    - typing-extensions >=4.8
    - xarray-datatree >=0.0.5
    - zarr >=2.0.0

test:
  imports:
    - xeofs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nicrie/xeofs
  summary: Collection of EOF analysis and related techniques for climate science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicrie
